# Generated by Django 6.0.5 on 2026-08-11 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='business_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number. Format: 09xxxxxxxxx', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='agency',
            name='license_number',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
